export enum Keys {
  Postgres = 'postrgres',
  TYPE = 'type',
  HOST = 'host',
  PORT = 'port',
  USERNAME = 'username',
  PASSWORD = 'password',
  DATABASE = 'database',
  NAMING_STRATEGY = 'namingStrategy',
  API_KEY = 'apiKey',
  JSW_TOKEN = 'jwtToken',
  APP = 'app',
  ENV = 'env',
  REQ_LIMIT = 'reqLimit',
  REMOTE_CSV = 'remoteCsv',
}
